### ISSUE TITLE
Unable to issue "system vmlicense upload" on Azure

### ISSUE THREAD

**Issue by JonTheNiceGuy** [fortinet-solutions-cse/40ansible#27]
I have built a `FortiGate NGFW - Single VM` on Azure using the marketplace and selecting the "BYOL 6.0.3" model. Following the build, I SSH in, and issue:
```
config system global
set admin-sport 443
end
exit
```

I then execute the following playbook:
```
---
- hosts: localhost
  vars:
    host_ip_address: 192.0.2.1
    host_user: someuser
    host_pass: 123_Somepass

  tasks:
  - name: Issue license
    fortiosconfig:
      host: "{{ host_ip_address }}"
      username: "{{ host_user }}"
      password: "{{ host_pass }}"
      vdom: "{{ host_vdom | default('root') }}"
      https: true
      config: system vmlicense upload
      action: upload
      config_parameters:
        filename: "./somefile.lic"
```

I get this as output:
```
(azure) vagrant@ubuntu:/HostHome/Documents/01 Projects - Ansible on Azure/Azure/2018-12-14_FGT_License$ ansible-playbook test.yml 
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] ********************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************
ok: [localhost]

TASK [Issue license] ****************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Exception: can not get following login
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1545039137.76-129793567464365/AnsiballZ_fortiosconfig.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1545039137.76-129793567464365/AnsiballZ_fortiosconfig.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1545039137.76-129793567464365/AnsiballZ_fortiosconfig.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_fortiosconfig_payload_nSoxNj/__main__.py\", line 845, in <module>\n  File \"/tmp/ansible_fortiosconfig_payload_nSoxNj/__main__.py\", line 833, in main\n  File \"/tmp/ansible_fortiosconfig_payload_nSoxNj/__main__.py\", line 756, in fortigate_config_upload\n  File \"/tmp/ansible_fortiosconfig_payload_nSoxNj/__main__.py\", line 469, in login\n  File \"/home/spriggsj/azure/local/lib/python2.7/site-packages/fortiosapi/fortiosapi.py\", line 130, in login\n    raise Exception('can not get following login')\nException: can not get following login\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP **************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```
The verbose output from the failure step is as follows:
```
TASK [Issue license] ****************************************************************************************************************************************************
task path: /HostHome/Documents/01 Projects - Ansible on Azure/Azure/2018-12-14_FGT_License/test.yml:9
The full traceback is:
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1545041674.57-132789405945393/AnsiballZ_fortiosconfig.py", line 113, in <module>
    _ansiballz_main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1545041674.57-132789405945393/AnsiballZ_fortiosconfig.py", line 105, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1545041674.57-132789405945393/AnsiballZ_fortiosconfig.py", line 48, in invoke_module
    imp.load_module('__main__', mod, module, MOD_DESC)
  File "/tmp/ansible_fortiosconfig_payload_nLR_hv/__main__.py", line 845, in <module>
  File "/tmp/ansible_fortiosconfig_payload_nLR_hv/__main__.py", line 833, in main
  File "/tmp/ansible_fortiosconfig_payload_nLR_hv/__main__.py", line 756, in fortigate_config_upload
  File "/tmp/ansible_fortiosconfig_payload_nLR_hv/__main__.py", line 469, in login
  File "/home/spriggsj/azure/local/lib/python2.7/site-packages/fortiosapi/fortiosapi.py", line 130, in login
    raise Exception('can not get following login')
Exception: can not get following login

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1545041674.57-132789405945393/AnsiballZ_fortiosconfig.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1545041674.57-132789405945393/AnsiballZ_fortiosconfig.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1545041674.57-132789405945393/AnsiballZ_fortiosconfig.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_fortiosconfig_payload_nLR_hv/__main__.py\", line 845, in <module>\n  File \"/tmp/ansible_fortiosconfig_payload_nLR_hv/__main__.py\", line 833, in main\n  File \"/tmp/ansible_fortiosconfig_payload_nLR_hv/__main__.py\", line 756, in fortigate_config_upload\n  File \"/tmp/ansible_fortiosconfig_payload_nLR_hv/__main__.py\", line 469, in login\n  File \"/home/spriggsj/azure/local/lib/python2.7/site-packages/fortiosapi/fortiosapi.py\", line 130, in login\n    raise Exception('can not get following login')\nException: can not get following login\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
```

Does this mean that because the license isn't valid at the time we try to make the API call, we're unable to use the API to deploy a license? Thanks!

**Comment by JonTheNiceGuy** [comment]
And it continues! 😁

I re-wrote the module to do an SSH connection to perform the license upload on the Azure image:

```
---
- hosts: localhost
  gather_facts: false
  vars:
    host: "192.0.2.1"
    username: someuser
    password: 123_Somepass
    vdom: root
    tftp_host: "203.0.113.1"
    tftp_file: "somefile.lic"
  tasks:
  - name: ssh cli cmd
    fortiosconfig:
      action: ssh
      host: "{{ host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      commands: |
                execute restore vmlicense tftp {{ tftp_file }} {{ tftp_host }}
                y
```

This didn't work, so I replaced the `commands:` block with this:

```
      commands: |
                execute restore vmlicense tftp {{ tftp_file }} {{ tftp_host }}\ny\n
```

Also didn't work. Using the expect module works however (it's not very clean, the expect module keeps issuing the same statements over and over agin - but it gets there!)...
```
---
- hosts: localhost
  gather_facts: false
  vars:
    host: "192.0.2.1"
    username: someuser
    password: 123_Somepass
    vdom: root
    tftp_host: "203.0.113.1"
    tftp_file: "somefile.lic"
  tasks:
  - name: ssh cli cmd
    expect:
      command: "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null {{ username }}@{{ host }}"
      responses:
        (?i)password: "{{ password }}"
        \x23: "execute restore vmlicense tftp {{ file }} {{ tftp_host }}"
        (?i)do: "y"
    register: expect_output
    failed_when: False
    changed_when: False
```

**Comment by thomnico** [comment]
Can you share the result of : 
 get system interface

on your fortigate please ?

**Comment by JonTheNiceGuy** [comment]
> 
> 
> Can you share the result of :
> get system interface
> 
> on your fortigate please ?

```
fgt01fw01 # get system interface
== [ port1 ]
name: port1   mode: dhcp    ip: 10.10.10.4 255.255.255.0   status: up    netbios-forward: disable    type: physical   netflow-sampler: disable    sflow-sampler: disable    scan-botnet-connections: disable    src-check: enable    mtu-override: disable    wccp: disable    drop-overlapped-fragment: disable    drop-fragment: disable
== [ port2 ]
name: port2   mode: static    ip: 0.0.0.0 0.0.0.0   status: up    netbios-forward: disable    type: physical   netflow-sampler: disable    sflow-sampler: disable    scan-botnet-connections: disable    src-check: enable    mtu-override: disable    wccp: disable    drop-overlapped-fragment: disable    drop-fragment: disable
== [ ssl.root ]
name: ssl.root   ip: 0.0.0.0 0.0.0.0   status: up    netbios-forward: disable    type: tunnel   netflow-sampler: disable    sflow-sampler: disable    scan-botnet-connections: disable    src-check: enable    wccp: disable
```

**Comment by mamunozgonzalez** [comment]
Hi @JonTheNiceGuy ,
 I see in your first playbook that you are trying to upload a license to a FGT and that you are setting "https: true". 

If the FGT does not have a license I guess it will not let you use HTTPS. So probably you have to set this to 'https: False'. Please also use uppercase False (or True) just to ensure they are fully compliant with Python.

Also please upgrade your local fortiosapi library: 
```pip install --upgrade fortiosapi```

I have just run a local example to update the license and seems to work fine. Maybe you can get an error in your playbook execution but the license should be installed in the system anyway.

Can you try previous suggestions and let us know the result?

**Comment by JonTheNiceGuy** [comment]
I'm right in the middle of some other stuff, but I'll get back to this shortly. Just to clarify though, even though the BYOL FortiGate models in Azure have no license attached, they do run HTTPS. That said, I suspect the API might not appreciate receiving anything before the license is attached... Like I said, I'll check this shortly.
